name:  Build x86 and arm Image

env:
  BASEIMAGE: kube-state-metrics:v2.0.3
  VERSION: 2.0.3

on:
  pull_request:
    branches:
      - exc-*
  push:
    branches:
      - ecx-*

jobs:
  docker-image:
    name: Build x86 and arm Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        run: make package